<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Authors>Brendan Connolly, Simon Baynes</Authors>
        <TargetFramework>netstandard2.0</TargetFramework>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/baynezy/Xunit.OpenCategories</PackageProjectUrl>
        <Description>Core functionality for Xunit.OpenCategories.</Description>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

</Project>