<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Authors>Brendan Connolly, Simon Baynes</Authors>
        <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/baynezy/Xunit.OpenCategories</PackageProjectUrl>
        <Description>Friendlier attributes to help categorise your tests.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>Xunit,Testing</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
        <IsPackable>true</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.1" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

</Project>
