on:
  workflow_call:
    inputs:
      version:
        description: 'The version number to use for the build'
        required: true
        type: string
      checkout-ref:
        description: 'The commit SHA to checkout'
        required: false
        default: ''
        type: string
      repository:
        description: 'The repository to checkout'
        required: false
        default: '${{ github.repository }}'
        type: string
  
jobs:
  build-libraries:
    runs-on: ubuntu-latest
    steps:
    - name: Log Branch
      run: |
        echo "Branch: ${{ inputs.checkout-ref }}"
    - name: Checkout Specific Ref
      if: ${{ inputs.checkout-ref != '' }}
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.checkout-ref }}
        repository: '${{ inputs.repository }}'
    - name: Checkout
      if: ${{ inputs.checkout-ref == '' }}
      uses: actions/checkout@v5
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5.0.0
      with:
        dotnet-version: 8.0.x
    - name: Restore
      uses: cake-build/cake-action@v3
      with:
        target: Restore
    - name: Build
      uses: cake-build/cake-action@v3
      with:
        target: Build
        arguments: |
          versionNumber: ${{inputs.version}}
    - name: Run tests
      uses: cake-build/cake-action@v3
      with:
        target: Test
        arguments: |
          testFilter: "UnitTests"
    - name: Publish Unit Test Results
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      with:
        files: "**/TestResults/*.xml"
    - name: Build NuGet Package
      uses: cake-build/cake-action@v3
      with:
        target: Pack
        arguments: |
          versionNumber: ${{inputs.version}}
    - name: Upload Package - v2
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: actions/upload-artifact@v5
      with:
        name: Xunit.OpenCategories
        path: ./src/Xunit.OpenCategories/bin/Release/*.nupkg
    - name: Upload Package - v3
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: actions/upload-artifact@v5
      with:
        name: Xunit.OpenCategories.V3
        path: ./src/Xunit.OpenCategories.V3/bin/Release/*.nupkg